# Generated by Django 5.1.3 on 2024-11-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='create_at',
        ),
        migrations.AddField(
            model_name='project',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
